#!/bin/bash
set -euo pipefail

################################################
# DoH Smart DNS — Kubernetes Deploy Script
# Generates ConfigMap from template and deploys
################################################

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

print_header() {
    echo ""
    echo -e "${BLUE}================================================${NC}"
    echo -e "${BLUE} $1${NC}"
    echo -e "${BLUE}================================================${NC}"
}

print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_warn()    { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error()   { echo -e "${RED}❌ $1${NC}"; }
print_info()    { echo -e "${BLUE}ℹ️  $1${NC}"; }

# --- Load VPS_IP ---
load_vps_ip() {
    if [ -n "${VPS_IP:-}" ]; then
        return 0
    fi

    if [ -f "$PROJECT_ROOT/.env" ]; then
        VPS_IP=$(grep '^VPS_IP=' "$PROJECT_ROOT/.env" 2>/dev/null | cut -d'=' -f2 | tr -d ' "'"'"'')
    fi

    if [ -z "${VPS_IP:-}" ]; then
        print_error "VPS_IP is not set."
        echo "  Set it in .env or pass as env variable:"
        echo "    VPS_IP=1.2.3.4 bash scripts/deploy.sh"
        exit 1
    fi
}

# --- Pre-flight checks ---
preflight() {
    print_header "Pre-flight Checks"

    if ! command -v kubectl &>/dev/null; then
        print_error "kubectl not found. Install it first:"
        echo "  https://kubernetes.io/docs/tasks/tools/"
        exit 1
    fi
    print_success "kubectl found"

    if ! kubectl cluster-info &>/dev/null; then
        print_error "Cannot connect to Kubernetes cluster."
        echo "  Make sure your kubeconfig is set up correctly."
        exit 1
    fi
    print_success "Connected to cluster: $(kubectl config current-context)"

    if command -v kustomize &>/dev/null; then
        KUSTOMIZE_CMD="kustomize build"
        print_success "kustomize found (standalone)"
    else
        KUSTOMIZE_CMD="kubectl kustomize"
        print_info "Using built-in kubectl kustomize"
    fi
}

# --- Generate xbox-hosts ConfigMap from template ---
generate_hosts_configmap() {
    print_header "Generating xbox-hosts ConfigMap"

    local template="$PROJECT_ROOT/coredns/xbox-hosts.template"
    local output="$PROJECT_ROOT/base/configmap-xbox-hosts.yaml"

    if [ ! -f "$template" ]; then
        print_error "Template not found: $template"
        exit 1
    fi

    local date_str
    date_str=$(date '+%Y-%m-%d %H:%M:%S %Z')

    # Generate hosts content from template
    local hosts_content
    hosts_content=$(sed \
        -e "s/__VPS_IP__/$VPS_IP/g" \
        -e "s/__DATE__/$date_str/g" \
        "$template")

    # Create ConfigMap YAML
    cat > "$output" <<EOF
# AUTO-GENERATED — Do not edit manually.
# Generated by: scripts/deploy.sh
# VPS IP: $VPS_IP
# Date: $date_str
apiVersion: v1
kind: ConfigMap
metadata:
  name: xbox-hosts
  namespace: doh-system
  labels:
    app.kubernetes.io/name: coredns-smartdns
    app.kubernetes.io/component: dns-hosts
    app.kubernetes.io/part-of: doh-smart-dns
data:
  xbox-hosts: |
$(echo "$hosts_content" | sed 's/^/    /')
EOF

    print_success "Generated xbox-hosts ConfigMap with VPS_IP=$VPS_IP"
    print_info "Output: $output"
}

# --- Create TLS Secret (if certs exist) ---
create_tls_secret() {
    print_header "TLS Certificate Setup"

    local cert_path=""
    local key_path=""

    # Check common cert locations
    for cert_dir in /etc/letsencrypt/live "${PROJECT_ROOT}/ssl"; do
        if [ -d "$cert_dir" ]; then
            # Try to find cert files
            local found_cert=$(find "$cert_dir" -name "fullchain.pem" -o -name "tls.crt" -o -name "cert.pem" 2>/dev/null | head -1)
            local found_key=$(find "$cert_dir" -name "privkey.pem" -o -name "tls.key" -o -name "key.pem" 2>/dev/null | head -1)
            if [ -n "$found_cert" ] && [ -n "$found_key" ]; then
                cert_path="$found_cert"
                key_path="$found_key"
                break
            fi
        fi
    done

    if [ -n "$cert_path" ] && [ -n "$key_path" ]; then
        print_info "Found cert: $cert_path"
        print_info "Found key:  $key_path"

        kubectl create secret tls doh-tls-certs \
            --namespace=doh-system \
            --cert="$cert_path" \
            --key="$key_path" \
            --dry-run=client -o yaml | kubectl apply -f -

        print_success "TLS secret created/updated"
    else
        print_warn "No TLS certificates found."
        echo "  Create them manually:"
        echo "    kubectl create secret tls doh-tls-certs \\"
        echo "      --namespace=doh-system \\"
        echo "      --cert=/path/to/fullchain.pem \\"
        echo "      --key=/path/to/privkey.pem"
        echo ""
        echo "  Or use cert-manager for automatic Let's Encrypt:"
        echo "    See README.md for cert-manager setup instructions."
        echo ""
        print_info "Continuing deployment (nginx will fail until certs are provided)..."
    fi
}

# --- Deploy to Kubernetes ---
deploy() {
    local overlay="${1:-base}"
    local manifest_dir="$PROJECT_ROOT/$overlay"

    if [ "$overlay" != "base" ]; then
        manifest_dir="$PROJECT_ROOT/overlays/$overlay"
    fi

    print_header "Deploying DoH Smart DNS ($overlay)"

    if [ ! -f "$manifest_dir/kustomization.yaml" ]; then
        print_error "Kustomization not found: $manifest_dir/kustomization.yaml"
        exit 1
    fi

    # Add the generated xbox-hosts configmap to kustomization if not already there
    if ! grep -q "configmap-xbox-hosts.yaml" "$PROJECT_ROOT/base/kustomization.yaml"; then
        # Insert before pdb.yaml
        sed -i 's|  - pdb.yaml|  - configmap-xbox-hosts.yaml\n  - pdb.yaml|' \
            "$PROJECT_ROOT/base/kustomization.yaml"
        print_info "Added configmap-xbox-hosts.yaml to kustomization"
    fi

    # Apply manifests
    print_info "Applying manifests from $manifest_dir..."
    $KUSTOMIZE_CMD "$manifest_dir" | kubectl apply -f -

    print_success "Manifests applied"

    # Wait for rollout
    print_header "Waiting for Rollout"

    echo -n "  CoreDNS:     "
    kubectl rollout status deployment/coredns-smartdns -n doh-system --timeout=120s 2>/dev/null && \
        print_success "Ready" || print_warn "Timeout (check pods)"

    echo -n "  DoH Backend: "
    kubectl rollout status deployment/doh-backend -n doh-system --timeout=120s 2>/dev/null && \
        print_success "Ready" || print_warn "Timeout (check pods)"

    echo -n "  Nginx:       "
    kubectl rollout status deployment/doh-nginx -n doh-system --timeout=120s 2>/dev/null && \
        print_success "Ready" || print_warn "Timeout (check pods)"
}

# --- Show status ---
show_status() {
    print_header "Deployment Status"

    echo ""
    echo "Pods:"
    kubectl get pods -n doh-system -o wide
    echo ""
    echo "Services:"
    kubectl get svc -n doh-system
    echo ""

    local node_ip
    node_ip=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}' 2>/dev/null)
    if [ -z "$node_ip" ]; then
        node_ip=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}' 2>/dev/null)
    fi

    print_header "Access Information"
    echo ""
    echo "  DNS (UDP/TCP):  ${node_ip:-<NODE_IP>}:30053"
    echo "  DoH (HTTPS):    https://${node_ip:-<NODE_IP>}:30443/dns-query"
    echo "  HTTP redirect:  http://${node_ip:-<NODE_IP>}:30080"
    echo ""
    echo "  Test DNS:  dig @${node_ip:-<NODE_IP>} -p 30053 xboxlive.com"
    echo "  Test DoH:  curl -ks https://${node_ip:-<NODE_IP>}:30443/health"
    echo ""
}

# --- Main ---
main() {
    local action="${1:-deploy}"
    local overlay="${2:-base}"

    case "$action" in
        deploy)
            load_vps_ip
            preflight
            generate_hosts_configmap
            create_tls_secret
            deploy "$overlay"
            show_status
            ;;
        status)
            show_status
            ;;
        destroy)
            print_header "Destroying DoH Smart DNS"
            kubectl delete namespace doh-system --ignore-not-found
            print_success "Namespace doh-system deleted"
            ;;
        generate)
            load_vps_ip
            generate_hosts_configmap
            print_success "ConfigMap generated (not applied)"
            ;;
        *)
            echo "Usage: $0 {deploy|status|destroy|generate} [base|production]"
            echo ""
            echo "Commands:"
            echo "  deploy [overlay]  Deploy to cluster (default: base)"
            echo "  status            Show current deployment status"
            echo "  destroy           Remove all DoH resources"
            echo "  generate          Generate xbox-hosts ConfigMap only"
            echo ""
            echo "Examples:"
            echo "  VPS_IP=1.2.3.4 $0 deploy"
            echo "  VPS_IP=1.2.3.4 $0 deploy production"
            echo "  $0 status"
            echo "  $0 destroy"
            exit 1
            ;;
    esac
}

main "$@"
