#!/bin/bash
set -euo pipefail

################################################
# DoH Smart DNS — Regenerate xbox-hosts ConfigMap
# Re-generates and hot-reloads the hosts file
# without redeploying the full stack.
#
# Usage:
#   bash scripts/regenerate-hosts.sh [VPS_IP]
#   VPS_IP=1.2.3.4 bash scripts/regenerate-hosts.sh
################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Resolve VPS_IP: arg > env > .env
VPS_IP="${1:-${VPS_IP:-}}"

if [ -z "$VPS_IP" ] && [ -f "$PROJECT_ROOT/.env" ]; then
    VPS_IP=$(grep '^VPS_IP=' "$PROJECT_ROOT/.env" 2>/dev/null | cut -d'=' -f2 | tr -d ' "'"'"'' || true)
fi

if [ -z "$VPS_IP" ]; then
    echo -e "${RED}❌ VPS_IP not set${NC}"
    echo "Usage: $0 [VPS_IP]"
    echo "   or: VPS_IP=1.2.3.4 $0"
    exit 1
fi

echo -e "${BLUE}Regenerating xbox-hosts ConfigMap with VPS_IP=$VPS_IP${NC}"

# Generate hosts file from template
TEMPLATE="$PROJECT_ROOT/coredns/xbox-hosts.template"
OUTPUT="$PROJECT_ROOT/base/configmap-xbox-hosts.yaml"
DATE_STR=$(date '+%Y-%m-%d %H:%M:%S %Z')

HOSTS_CONTENT=$(sed -e "s/__VPS_IP__/$VPS_IP/g" -e "s/__DATE__/$DATE_STR/g" "$TEMPLATE")

cat > "$OUTPUT" <<EOF
# AUTO-GENERATED by regenerate-hosts.sh — $DATE_STR
apiVersion: v1
kind: ConfigMap
metadata:
  name: xbox-hosts
  namespace: doh-system
  labels:
    app.kubernetes.io/name: coredns-smartdns
    app.kubernetes.io/component: dns-hosts
    app.kubernetes.io/part-of: doh-smart-dns
data:
  xbox-hosts: |
$(echo "$HOSTS_CONTENT" | sed 's/^/    /')
EOF

echo -e "${GREEN}✅ ConfigMap generated${NC}"

# Apply just the ConfigMap
echo -e "${BLUE}Applying ConfigMap...${NC}"
kubectl apply -f "$OUTPUT"

# Restart CoreDNS to pick up new hosts
echo -e "${BLUE}Restarting CoreDNS pods...${NC}"
kubectl rollout restart deployment/coredns-smartdns -n doh-system
kubectl rollout status deployment/coredns-smartdns -n doh-system --timeout=60s

echo -e "${GREEN}✅ xbox-hosts updated and CoreDNS restarted${NC}"
echo ""
echo "Test: dig @\$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}') -p 30053 xboxlive.com"
