apiVersion: apps/v1
kind: Deployment
metadata:
  name: doh-backend
  namespace: doh-system
  labels:
    app.kubernetes.io/name: doh-backend
    app.kubernetes.io/component: doh-server
    app.kubernetes.io/part-of: doh-smart-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: doh-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doh-backend
        app.kubernetes.io/component: doh-server
        app.kubernetes.io/part-of: doh-smart-dns
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: doh-backend
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      containers:
        - name: doh-server
          image: satishweb/doh-server:v2.3.5
          env:
            - name: UPSTREAM_DNS_SERVER
              value: "udp:coredns-smartdns.doh-system.svc.cluster.local:53"
            - name: DOH_HTTP_PREFIX
              value: "/dns-query"
            - name: DOH_SERVER_LISTEN
              value: ":8053"
            - name: DOH_SERVER_TIMEOUT
              value: "5"
            - name: DOH_SERVER_TRIES
              value: "3"
          ports:
            - containerPort: 8053
              name: doh-http
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8053
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8053
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: doh-backend
  namespace: doh-system
  labels:
    app.kubernetes.io/name: doh-backend
    app.kubernetes.io/component: doh-server
    app.kubernetes.io/part-of: doh-smart-dns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: doh-backend
  ports:
    - port: 8053
      targetPort: 8053
      protocol: TCP
      name: doh-http
