apiVersion: apps/v1
kind: Deployment
metadata:
  name: doh-nginx
  namespace: doh-system
  labels:
    app.kubernetes.io/name: doh-nginx
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: doh-smart-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: doh-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doh-nginx
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: doh-smart-dns
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: doh-nginx
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && nginx -s quit"]
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: tls-certs
              mountPath: /etc/nginx/ssl
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
            - name: cache
              mountPath: /var/cache/nginx
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: tls-certs
          secret:
            secretName: doh-tls-certs
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: cache
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: doh-nginx
  namespace: doh-system
  labels:
    app.kubernetes.io/name: doh-nginx
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: doh-smart-dns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: doh-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
      name: https
